#!/usr/bin/env python3
"""
Query dasgoclient for nevents and nfiles for all DBSSample datasets.
Outputs a Python dictionary to das_nevents.py for use in submit.py.
"""

import subprocess
import re
import json
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

def extract_datasets(filename):
    """Extract all DBSSample dataset strings from a Python file."""
    datasets = set()
    with open(filename) as f:
        for line in f:
            # Skip commented-out lines
            stripped = line.lstrip()
            if stripped.startswith("#"):
                continue
            matches = re.findall(r'DBSSample\(dataset="([^"]+)"', line)
            for m in matches:
                if m:
                    datasets.add(m)
    return sorted(datasets)

def query_das(dataset):
    """Query dasgoclient for nevents and nfiles for a dataset."""
    try:
        # Query nevents
        result_nevents = subprocess.run(
            ["dasgoclient", "-query", f"dataset={dataset} | grep dataset.nevents"],
            capture_output=True, text=True, timeout=120
        )
        nevents = int(result_nevents.stdout.strip()) if result_nevents.stdout.strip() else 0

        # Query nfiles
        result_nfiles = subprocess.run(
            ["dasgoclient", "-query", f"dataset={dataset} | grep dataset.nfiles"],
            capture_output=True, text=True, timeout=120
        )
        nfiles = int(result_nfiles.stdout.strip()) if result_nfiles.stdout.strip() else 0

        return dataset, nevents, nfiles
    except Exception as e:
        print(f"ERROR querying {dataset}: {e}", file=sys.stderr)
        return dataset, -1, -1

def main():
    mc_file = "vbsvvh_mc.py"
    datasets = extract_datasets(mc_file)
    print(f"Found {len(datasets)} unique active DBSSample datasets", file=sys.stderr)

    results = {}
    completed = 0
    total = len(datasets)

    with ThreadPoolExecutor(max_workers=20) as executor:
        futures = {executor.submit(query_das, ds): ds for ds in datasets}
        for future in as_completed(futures):
            dataset, nevents, nfiles = future.result()
            results[dataset] = {"nevents": nevents, "nfiles": nfiles}
            completed += 1
            if completed % 50 == 0 or completed == total:
                print(f"Progress: {completed}/{total}", file=sys.stderr)

    # Write output as a Python dict
    with open("das_nevents.py", "w") as f:
        f.write("# Auto-generated by query_das_nevents.py\n")
        f.write("# Dictionary of {dataset: {nevents, nfiles}} from dasgoclient\n\n")
        f.write("das_info = {\n")
        for ds in sorted(results.keys()):
            info = results[ds]
            evts_per_file = info["nevents"] // info["nfiles"] if info["nfiles"] > 0 else 0
            f.write(f'    "{ds}": {{"nevents": {info["nevents"]}, "nfiles": {info["nfiles"]}, "evts_per_file": {evts_per_file}}},\n')
        f.write("}\n")

    print(f"\nWrote das_nevents.py with {len(results)} entries", file=sys.stderr)

    # Print summary of any failures
    failures = {k: v for k, v in results.items() if v["nevents"] <= 0}
    if failures:
        print(f"\nWARNING: {len(failures)} datasets had issues:", file=sys.stderr)
        for ds in sorted(failures.keys()):
            print(f"  {ds}", file=sys.stderr)

if __name__ == "__main__":
    main()
